### ISSUE TITLE
Exception while invoking method 'createConversation' Error: Conversation id must be a string

### ISSUE THREAD

**Issue by Fen747** [copleykj/socialize-messaging#24] opened 2017-01-06 23:38 UTC
When  calling `const conversation = new Conversation().save();` on client, I get a denied insert right, and when I call it on server, I get back the error `Exception while invoking method 'createConversation' Error: Conversation id must be a string` from collection2 package.

Anything I'm doing wrong ? The doc doesn't specify anything about where to use the API.

My code :

// /imports/api/methods
```
Meteor.methods({
	createConversation(){
		const _conversation = new Conversation();
		const conversation = _conversation.save();
		
		log(_conversation);
		log(conversation);
	}
});
```

// /imports/ui/components/home.js
```
Template.home.events({
	'click #js-create-conv': function ( event, instance ) {
  	Meteor.call("createConversation", ( error, response ) => {} );
	}
});
```

// /imports/ui/components/home.html
```
<template name='home'>
	<a id="js-create-conv">Create conversation</a>
</template>
```

Thank you.

**Comment by copleykj** [comment] 2017-01-07 05:50
Do you have a full stack trace for the error?

**Comment by copleykj** [comment] 2017-01-07 06:13
Also if possible a full reproduction would be very helpful.

**Comment by Fen747** [comment] 2017-01-07 12:29
[Here is the repo](https://github.com/Fen747/socialize-issue)

And here is the full stack trace :
```

```

**Comment by copleykj** [comment] 2017-01-09 04:24
Ok, so this has to do with something that MDG changed in the mongo driver for 1.4 that affected the collection hooks package. It's been fixed in the collection-hooks package but I've not done a release since and therefore things are still using the old package. running `meteor add matb33:collectionhooks@0.8.4` will fix the issue until I get everything set up for a new release.

**Comment by Fen747** [comment] 2017-01-09 14:44
Great, thanks a lot Copleykj !

**Comment by copleykj** [comment] 2017-01-09 15:46
No problem.

**Closed by copleykj** 2017-01-09 15:46 UTC
